### ISSUE TITLE
Hitting Enter key should submit form on 'Compare Word Frequencies' page

### ISSUE THREAD

**Issue by cjaiello** [cjaiello/Analyzing-29-Years-of-Jeopardy-Questions#2]
![Screen Shot 2020-09-22 at 7 06 00 PM](https://user-images.githubusercontent.com/5159844/93946232-bbc36f80-fd06-11ea-94ab-5fc47d784cf2.png)

Users should be able to submit form either by clicking the button or by hitting enter.

**Comment by gmgalvan** [comment]
Hi can I help with that issue?, I have a PR ready to review.
